name: proxmity_alarm
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  fast_color_picker: ^0.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.2.0
  flutter_map_location_marker: ^7.0.0
  flutter_map: ^5.0.0
  geolocator: ^9.0.2
  get: ^4.6.5
  latlong2: any
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  vibration: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  lint: ^2.1.2

flutter:
  uses-material-design: true

  assets:
  - assets/
