name: location_alarm
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  fast_color_picker: ^0.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.2.0
  flutter_map: ^6.1.0
  geolocator: ^10.1.0
  latlong2: any
  uuid: ^4.3.3
  vibration: ^1.8.1
  flutter_map_cancellable_tile_provider: ^2.0.0
  path_provider: ^2.1.2
  flutter_map_cache: ^1.4.3
  flutter_map_location_marker: ^8.0.4
  feedback: ^3.0.0
  sentry_flutter: ^7.16.0
  flutter_email_sender: ^6.0.2
  feedback_sentry: ^3.0.0
  dio_cache_interceptor_file_store: ^1.2.3
  dio_cache_interceptor: ^3.5.0
  june: ^0.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  lint: ^2.1.2
  dependency_validator: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
  - assets/
