name: proxalarm
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  url_launcher: ^6.1.11
  latlong2: any
  get: ^4.6.5
  uuid: ^3.0.7
  fast_color_picker: ^0.1.1
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
